workflows:
  my-ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build iOS Simulator
        script: |
          # Bu komut sanal telefonlar için derleme yapar
          flutter build ios --simulator --debug
      - name: Zip .app for Appetize
        script: |
          # Oluşan .app dosyasını zip haline getiriyoruz
          cd build/ios/iphonesimulator
          zip -r ios-app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/*.zip