name: kuyumcu_app
description: "Aslanoğlu Kuyumculuk canlı altın ve döviz takip uygulaması."

publish_to: 'none'


version: 2.0.0+5

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.3

  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

  adaptive_icon_background: "#0A0F1F"
  adaptive_icon_foreground: "assets/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/splash_logo.png